#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

echo "=== HR System setup ==="
echo

read -rp "ใส่ domain/subdomain สำหรับ n8n เช่น hr.example.com: " N8N_DOMAIN
if [[ -z "${N8N_DOMAIN}" ]]; then
  echo "ERROR: ต้องใส่ domain"
  exit 1
fi

read -rp "ใส่ email สำหรับ Let's Encrypt เช่น you@example.com: " ACME_EMAIL
if [[ -z "${ACME_EMAIL}" ]]; then
  echo "ERROR: ต้องใส่ email"
  exit 1
fi

gen_secret() {
  openssl rand -base64 36 | tr -d '\n' | tr '/+' 'AZ' | cut -c1-40
}

POSTGRES_PASSWORD="$(gen_secret)"
N8N_DB_PASSWORD="$(gen_secret)"
N8N_ENCRYPTION_KEY="$(openssl rand -hex 32)"
N8N_BASIC_AUTH_USER="admin"
N8N_BASIC_AUTH_PASSWORD="$(gen_secret)"

cat > .env <<EOF
# Generated by setup.sh
N8N_DOMAIN=${N8N_DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

POSTGRES_DB=hr_system
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

N8N_DB_USER=n8n_user
N8N_DB_PASSWORD=${N8N_DB_PASSWORD}
N8N_DB_SCHEMA=n8n

N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

GENERIC_TIMEZONE=Asia/Bangkok
TZ=Asia/Bangkok

LINE_CHANNEL_ACCESS_TOKEN=PASTE_LINE_TOKEN_HERE
LINE_CHANNEL_SECRET=PASTE_LINE_SECRET_HERE
OPENAI_API_KEY=PASTE_OPENAI_KEY_HERE
EOF

chmod 600 .env

mkdir -p postgres/data postgres/init n8n/data caddy/data caddy/config backups local-files
chmod -R 700 postgres n8n backups || true

echo
echo "✅ สร้าง .env แล้ว"
echo
echo "เก็บรหัสนี้ไว้:"
echo "n8n URL:      https://${N8N_DOMAIN}"
echo "n8n user:     ${N8N_BASIC_AUTH_USER}"
echo "n8n password: ${N8N_BASIC_AUTH_PASSWORD}"
echo
echo "ขั้นต่อไป:"
echo "docker compose up -d"
