#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${N8N_DB_USER}') THEN
    CREATE ROLE ${N8N_DB_USER} LOGIN PASSWORD '${N8N_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${N8N_DB_USER} WITH PASSWORD '${N8N_DB_PASSWORD}';
  END IF;
END
\$\$;

CREATE SCHEMA IF NOT EXISTS ${N8N_DB_SCHEMA} AUTHORIZATION ${N8N_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${N8N_DB_USER};
GRANT ALL ON SCHEMA ${N8N_DB_SCHEMA} TO ${N8N_DB_USER};
GRANT ALL ON SCHEMA public TO ${N8N_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${N8N_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${N8N_DB_USER};
SQL
